server:
   port: 7075

Spring:
   datasource:
      url: jdbc:mysql://localhost:3306/sample
      driverClassName: com.mysql.cj.jdbc.Driver
      username: mohit
      password: mohit
      maxPoolSize: 20
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
        
   h2:
      console:
         enabled: true
